shethTishaA1: shethTishaA1.o shethTishaA1Main.o
	gcc -Wall -std=c99 shethTishaA1.o shethTishaA1Main.o -o shethTishaA1
shethTishaA1.o: shethTishaA1.c givenA1.h
	gcc -Wall -std=c99 -c shethTishaA1.c
shethTishaA1Main.o: shethTishaA1Main.c givenA1.h
	gcc -Wall -std=c99 -c shethTishaA1Main.c
clean:
	rm *.o shethTishaA1
